### ISSUE TITLE
Change Text in Welcome Page

### ISSUE THREAD

**Issue by stefanbuttigieg** [COVID19-Malta/covid19check#24]
Change text from:

"This short questionnaire will help assess your risk of being infected and provides recommendations based on your situation.

Your answers in turn help the Maltese Superintendence of Public Health assess and predict the spread of the virus in Malta.

By answering the survey, you will receive further suggestions on how to behave in your situation."

to 

"These questions will help assess your risk of being infected and provides guidance based on your situation.

Your answers, in turn, help the Superintendence of Public Health assess and predict the spread of the virus in Malta.

By answering the questions, you will receive further suggestions on how to behave in your situation."

**Comment by jp-um** [comment]
Please update the issue/text (since we are going to remove the IP logging).

**Comment by stefanbuttigieg** [comment]
Done

**Comment by jp-um** [comment]
Fixed.  Please test and close @stefanbuttigieg.
