### ISSUE TITLE
Update Locality List

### ISSUE THREAD

**Issue by stefanbuttigieg** [COVID19-Malta/covid19check#27]
Add Hamlets to the List of Localities. Full updated list below

[Copy of Localities_26Apr20.xlsx](https://github.com/COVID19-Malta/coronatest/files/4536075/Copy.of.Localities_26Apr20.xlsx)

The locations to be added are:
Baħrija
Bubaqra
Fleur-de-Lys
Gwardamanġa
Ħal Farruġ
Madliena
Magħtab
Manikata
Marsalforn
Paceville
Santa Venera
St Peter's
Swatar
Tal-Virtù
Xlendi
Żebbiegħ

Map the following to their specific location rather than by Local Council
Baħar iċ-Ċagħaq
San Pawl tat-Tarġa
L-Ibraġ
Burmarrad
Xemxija
Qawra

Differentiate between Mġarr(Malta) u Mġarr(Għawdex), Santa Luċija(Malta) and Santa Luċija(Għawdex)

**Comment by jp-um** [comment]
**Fixed.**  Please test & close.

**Comment by stefanbuttigieg** [comment]
Excellent. Thank you
