### ISSUE TITLE
Update Final Outcomes

### ISSUE THREAD

**Issue by stefanbuttigieg** [COVID19-Malta/covid19check#28]
Update final outcomes, the advice given at the end with the following outcomes shown in the attached document
[Risk Assessment Tool Scenarios - clean_nocomments.docx](https://github.com/COVID19-Malta/covid19check/files/4542047/Risk.Assessment.Tool.Scenarios.-.clean_nocomments.docx)

Further recommendations and suggestions of what needs to be removed and modified in terms of JSON in the word document below: 
[jp guidance updates to scenarios.docx](https://github.com/COVID19-Malta/covid19check/files/4542094/jp.guidance.updates.to.scenarios.docx)

**Comment by jp-um** [comment]
Should now be fixed.  Please test **each** scenario according to the document and let me know.  Note that this is a major change.

**Comment by stefanbuttigieg** [comment]
Scenario 1 - Test Passed
Scenario 2 - Test Passed
Scenario 3 - Test Passed
Scenario 4 - Test Passed
Scenario 5 - Test Passed
Scenario 6 - Workflow to be reviewed
Scenario 7 - Remove Point 2 (Close Contact)
Scenario 8 - Test Passed
Scenario 9 - Test Passed
Scenario 10 - "scenario_call_111_if_symptoms" to be rendered correctly otherwise correct
Scenario 11 -  Workflow to be reviewed
Scenario 12 - To add as point 4 -> If you were in close contact with a COVID-19 case, you should remain in quarantine for two weeks from the date you were in contact with a confirmed COVID-19 case

**Comment by stefanbuttigieg** [comment]
Scenario 6 and 11 sorted with other.....can we double-check Scenario 10

**Comment by stefanbuttigieg** [comment]
Scenario 6 - Test Passed
Scenario 7 - Test Passed
Scenario 11 - Test Passed

**Comment by jp-um** [comment]
_Scenario_10_ missing action should now be fixed.  Test and close @stefanbuttigieg.
