### ISSUE TITLE
Update App Authors

### ISSUE THREAD

**Issue by stefanbuttigieg** [COVID19-Malta/covid19check#31]
Update App Authors to move up "Maltese customizations by" and include : Dr Stefan Buttigieg(Ministry for Health), Dr Hugo Agius Muscat(Ministry for Health) and Mr Mark Captur(MITA)

**Comment by jp-um** [comment]
Should be fixed.  I lest the Estonian folks first, this is their app after all ... Also, I removed the titles since no one else has them.

**Comment by stefanbuttigieg** [comment]
Prosit. Ideja tajba :)
