### ISSUE TITLE
Add Unit 'celsius' following Temperature

### ISSUE THREAD

**Issue by stefanbuttigieg** [COVID19-Malta/covid19check#41]
To Add Unit 'celsius' following Temperature field

**Comment by SimonTheuma** [comment]
![image](https://user-images.githubusercontent.com/904480/81204617-c4badb00-8fc9-11ea-8d11-ecb781b790cc.png)

is this what you wanted @stefanbuttigieg ?

**Comment by stefanbuttigieg** [comment]
yes that's perfect @SimonTheuma

**Comment by SimonTheuma** [comment]
Ok will push in a bit. I think there are still a lot of people using
farenheit so we can say anything over 85 is automatically F perhaps.

**Comment by stefanbuttigieg** [comment]
maybe we should give a choice somehow? But then would need to register on db an additional field for whether it was farenheit or Celsius

**Comment by jp-um** [comment]
Thanks Simon!
—

*Dr Jean-Paul Ebejer**,*  BSc (Hons) (Melita), MSc (Imperial), DPhil (Oxon.)

*Lecturer*
Centre for Molecular Medicine and BioBanking,
Office 320, Biomedical Sciences Building,
University of Malta, Msida, MSD 2080.  MALTA.
T: (00356) 2340 3263

Where am I? <https://bitsilla.com/blog/where-to-find-me/>

<https://twitter.com/malteseunderdog>

**Comment by stefanbuttigieg** [comment]
Let's stick to Celsius then will focus on data cleaning if necessary

**Comment by stefanbuttigieg** [comment]
well done to all. This has been sorted
